# Generated by Django 4.2.18 on 2025-02-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_alter_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cpriority',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='ctype',
            field=models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('task', 'Task'), ('enhancement', 'Enhancement'), ('security', 'Security Issue')], max_length=45, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('commentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.comment')),
                ('issueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
