# Generated by Django 4.2.18 on 2025-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_issue_cpriority_alter_issue_ctype_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cdescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
